---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: dumpling
spec:
  memberOf: [dupi]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: pillow
spec:
  memberOf: [dupi]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: dupi
spec:
  type: team
  children: []
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: coffee-supply-chain
spec:
  owner: dupi
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: roaster-backend
  description: The place to roast, turn, and cool the beans
  labels:
    example.com/coffee-stage: processing
  annotations:
    example.com/service-discovery: roasterbk
    backstage.io/source-location: url:https://github.com/all-boundaries/coffee-store
    backstage.io/techdocs-ref: url:https://github.com/all-boundaries/coffee-store/blob/main
    github.com/project-slug: all-boundaries/coffee-store
  tags:
    - java
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  owner: dupi
  type: service
  lifecycle: production
  system: coffee-supply-chain
  providesApis:
    - default/roaster-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: roaster-api
  description: HTTP API for managing roasting
spec:
  owner: dupi
  type: openapi
  lifecycle: production
  system: coffee-supply-chain
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Roaster API
      license:
        name: MIT
    servers:
      - url: https://google.com
    paths:
      /batches:
        get:
          summary: List all batches in roasting process
